### ISSUE TITLE
Monaca Preview has errors

### ISSUE THREAD

**Issue by pablomatgar** [pablomatgar/Japanese-Sign-Language-Interpreter#12]
### Bug description

Build in Monaca Preview does not work. The following error is encountered:

**Bug screenshot:**

<img width="994" alt="bug screenshot" src="https://user-images.githubusercontent.com/34125654/158163357-894a57da-cdc5-4d13-99cb-b0de6868f339.png">

According to Google, this error is caused because of the Node.js version, but I don't know how to change it in Monaca preview.

**Resources:**

https://stackoverflow.com/questions/69665780/error-err-unsupported-esm-url-scheme-only-file-and-data-urls-are-supported-by

https://github.com/vercel/next.js/discussions/29080

https://www.angularfix.com/2022/01/error-errunsupportedesmurlscheme-only.html

### Correct behaviour

This error should not appear and Monaca Preview should build the app without errors.

### How to reproduce

Upload the project to Monaca Cloud and check the Preview.

**Comment by yong-asial** [comment]
@pablomatgar i confirmed it is working fine on Monaca Cloud IDE if we upgrade Node version to 16. Since we are planning to release Cordova 11 support (Node 16) this week, we don't have to fix this issue. Let's do following
- upgrade this project to Cordova 11
- wait to release this Github/blog after Monaca release Cordova 11 support (Node 16)

**Comment by pablomatgar** [comment]
Okay, let's do it then @yong-asial
